# Set update schedule for GitHub Actions
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for pip/poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain submodule versions
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
